apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argo-app.yaml
- cube-ci.yaml
- cube-ci-production.yaml
- env/cube-cd-development.yaml
- env/cube-cd-qa.yaml
- env/cube-cd-production.yaml
- cube-project.yaml
- baseimage.yaml
